# Hardcoded
fxbuilding=fx_building.ogg
fxcaravan=fx_caravan.ogg
fxclick=fx_click.ogg
fxdead=fx_deadenemy.ogg
fxeat=fx_eat.ogg
fxmine=fx_mine.ogg
fxnewhero=fx_guitar2.ogg
fxnewimmigrants=fx_guitar.ogg
musicIG=music_IG.ogg
musicMM=music_MM.ogg

# Non-hardcoded (scripted)
fxchop=fx_chop.ogg
fxchorus=fx_chorus.ogg
fxdeadfemale=fx_deadfemale.ogg
fxdeadmale=fx_deadmale.ogg
fxnighttime=fx_nightime.ogg
fxrooster=fx_rooster.ogg
